import Foundation

// MARK: - Pomodoro

/// Focus and break lengths. A long break replaces the short one after every `rounds` focuses.
public struct PomodoroPlan: Equatable, Sendable {
    public var focus: TimeInterval
    public var shortBreak: TimeInterval
    public var longBreak: TimeInterval
    public var rounds: Int

    public init(focus: TimeInterval = 25 * 60, shortBreak: TimeInterval = 5 * 60, longBreak: TimeInterval = 15 * 60, rounds: Int = 4) {
        self.focus = focus
        self.shortBreak = shortBreak
        self.longBreak = longBreak
        self.rounds = max(1, rounds)
    }

    public func duration(of phase: PomodoroPhase) -> TimeInterval {
        switch phase {
        case .focus: focus
        case .shortBreak: shortBreak
        case .longBreak: longBreak
        }
    }

    public func next(after phase: PomodoroPhase) -> PomodoroPhase {
        switch phase {
        case .focus(let round): round % rounds == 0 ? .longBreak(after: round) : .shortBreak(after: round)
        case .shortBreak(let round): .focus(round: round + 1)
        case .longBreak: .focus(round: 1)
        }
    }
}

public enum PomodoroPhase: Equatable, Sendable {
    case focus(round: Int)
    case shortBreak(after: Int)
    case longBreak(after: Int)

    public var isBreak: Bool {
        if case .focus = self { return false }
        return true
    }

    /// "Focus 2 of 4", "Short break", "Long break".
    public func title(rounds: Int) -> String {
        switch self {
        case .focus(let round): "Focus \((round - 1) % max(1, rounds) + 1) of \(rounds)"
        case .shortBreak: "Short break"
        case .longBreak: "Long break"
        }
    }
}

// MARK: - Clipboard

/// What a copied piece of text is, for its quick action.
public enum ClipKind: Equatable, Sendable {
    case text, link(URL), email, color(r: Double, g: Double, b: Double)

    public static func detect(_ s: String) -> ClipKind {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains(where: \.isNewline), t.count <= 2048 else { return .text }
        if let url = URL(string: t), let scheme = url.scheme?.lowercased(), scheme == "https" || scheme == "http",
           url.host?.contains(".") == true, !t.contains(" ") {
            return .link(url)
        }
        if t.range(of: #"^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$"#, options: [.regularExpression, .caseInsensitive]) != nil {
            return .email
        }
        if t.range(of: #"^#([0-9a-f]{3}|[0-9a-f]{6})$"#, options: [.regularExpression, .caseInsensitive]) != nil {
            var hex = String(t.dropFirst())
            if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }
            let v = Int(hex, radix: 16) ?? 0
            return .color(r: Double((v >> 16) & 0xFF) / 255, g: Double((v >> 8) & 0xFF) / 255, b: Double(v & 0xFF) / 255)
        }
        return .text
    }
}

public enum ClipboardPolicy {
    /// Pasteboard types that mean "don't record this": the nspasteboard.org markers used by
    /// password managers and other apps, plus older ones still in use.
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type", "net.antelle.keeweb",
    ]

    public static func shouldRecord(types: [String]) -> Bool {
        !types.contains(where: ignoredTypes.contains)
    }

    /// Longest text kept per item.
    public static let maxLength = 20_000
}

/// Recent clipboard text, newest first: pinned items stay, the rest are capped.
public struct ClipHistory: Equatable, Sendable {
    public struct Item: Equatable, Sendable, Identifiable {
        public let id: UUID
        public var text: String
        public var pinned: Bool
        public var date: Date

        public init(id: UUID = UUID(), text: String, pinned: Bool = false, date: Date = Date()) {
            self.id = id
            self.text = text
            self.pinned = pinned
            self.date = date
        }

        public var kind: ClipKind { ClipKind.detect(text) }
    }

    public private(set) var items: [Item] = []
    public var limit: Int

    public init(items: [Item] = [], limit: Int = 30) {
        self.items = items
        self.limit = limit
    }

    /// Adds a copy. Copying the same text again moves it to the top (keeping its pin).
    public mutating func add(_ text: String, at date: Date = Date()) {
        let clipped = String(text.prefix(ClipboardPolicy.maxLength))
        guard !clipped.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        var item = Item(text: clipped, date: date)
        if let i = items.firstIndex(where: { $0.text == clipped }) {
            item = items.remove(at: i)
            item.date = date
        }
        items.insert(item, at: 0)
        var unpinned = 0
        items = items.filter { item in
            if item.pinned { return true }
            unpinned += 1
            return unpinned <= limit
        }
    }

    public mutating func togglePin(_ id: UUID) {
        if let i = items.firstIndex(where: { $0.id == id }) { items[i].pinned.toggle() }
    }

    public mutating func remove(_ id: UUID) { items.removeAll { $0.id == id } }

    /// Clears everything except pins.
    public mutating func clear() { items.removeAll { !$0.pinned } }

    public var pinned: [Item] { items.filter(\.pinned) }
}
